
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyCfciFB-AZSA716FhRXm-9yzj-kfA35wIA",
    appId: "1:178214932315:web:6f38911fc42321082d547e",
    messagingSenderId: "178214932315",
    projectId: "fyndeg-d1f50",
    authDomain: "fyndeg-d1f50.firebaseapp.com",
    storageBucket: "fyndeg-d1f50.appspot.com",
      measurementId: "G-QJ8RCK3MPD"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyCfciFB-AZSA716FhRXm-9yzj-kfA35wIA",
    appId: "1:178214932315:web:6f38911fc42321082d547e",
    messagingSenderId: "178214932315",
    projectId: "fyndeg-d1f50",
    storageBucket: "fyndeg-d1f50.appspot.com",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyCfciFB-AZSA716FhRXm-9yzj-kfA35wIA",
    appId: "1:178214932315:web:6f38911fc42321082d547e",
    messagingSenderId: "178214932315",
    projectId: "fyndeg-d1f50",
    storageBucket: "fyndeg-d1f50.appspot.com",
    androidClientId: '',
    iosClientId: '',
    iosBundleId: '',
  );
}
