
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBK8RLb7qiEOC1v3tIoAZOneSIqNpLRFsQ",
      appId: "1:378282776139:web:a2fdfd8f1c5a8fb8379fce",
      messagingSenderId: "378282776139",
      projectId: "fyndeg-7cbc3",
    authDomain: "fyndeg-7cbc3.firebaseapp.com",
      storageBucket: "fyndeg-7cbc3.appspot.com",
      measurementId: "G-E6Z1X70GF1"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyBK8RLb7qiEOC1v3tIoAZOneSIqNpLRFsQ",
    appId: "1:378282776139:web:a2fdfd8f1c5a8fb8379fce",
    messagingSenderId: "378282776139",
    projectId: "fyndeg-7cbc3",
    storageBucket: "fyndeg-7cbc3.appspot.com",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyBK8RLb7qiEOC1v3tIoAZOneSIqNpLRFsQ",
    appId: "1:378282776139:web:a2fdfd8f1c5a8fb8379fce",
    messagingSenderId: "378282776139",
    projectId: "fyndeg-7cbc3",
    storageBucket: "fyndeg-7cbc3.appspot.com",
    androidClientId: '',
    iosClientId: '',
    iosBundleId: '',
  );
}
